apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-app-test
spec:
  selector:
    matchLabels:
      app: hackathon-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hackathon-app
    spec:
      containers:
      - name: hackathon-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
